### ISSUE TITLE
Use GitHub Packages NuGet Registry

### ISSUE THREAD

**Issue by FelixS90** [ZEISS/czicompress#26]
**Is your feature request related to a problem? Please describe.**
- no clean SBOM generation and supply chain management possible due to manual (locally driven by update script) update process of libczicompressc -> Related to #7 
- currently need to store dll in code

**Describe the solution you'd like**
Using GitHub Packages NuGet registry to push from [libczicompress build in GitHub action](https://github.com/ZEISS/czicompress/actions/workflows/czicompress_cmake.yml). Consumption in [czishrink](https://github.com/ZEISS/czicompress/actions/workflows/czishrink_dotnet.yml) from there.

**Additional context**
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry
https://github.blog/changelog/2022-12-09-packages-fine-grained-permissions-and-organization-level-publishing-are-now-available-for-the-github-packages-nuget-registry/

**Comment by m-ringler** [comment]
@FelixS90 One thing that we should keep in mind here: we don't want to unduly complicate branching and forking the repo. I'd say that
* It must remain possible to use the CziShrink CI build and the czicompress CI build of a repo fork without setting up  a personal access token and/or altering the nuget package registry location in the forked repo.
* It should remain easy to substitute a locally built libczicompressc nuget package in CziShrink for development purposes.
* It should remain possible to build CziShrink on your local dev box without authenticating to the github nuget package registry.

**Comment by m-ringler** [comment]
Also, if the libczicompressc nuget package gets a 'life of its own', we should make the nuspec a bit more complete (esp. description) and address the warnings issued by nuget pack.

**Comment by FelixS90** [comment]
Closing. Staying with current way of deployment - in combination with #7 .
