### ISSUE TITLE
Make use of path filters for GitHub actions

### ISSUE THREAD

**Issue by FelixS90** [ZEISS/czicompress#29]
**Is your feature request related to a problem? Please describe.**
The following pipelines are currently triggered/running regardless whether there is a change justifying a run:

https://github.com/ZEISS/czicompress/actions/workflows/czicompress_cmake.yml
https://github.com/ZEISS/czicompress/actions/workflows/czishrink_dotnet.yml
https://github.com/ZEISS/czicompress/actions/workflows/czicompress_codeql.yml
https://github.com/ZEISS/czicompress/actions/workflows/czishrink_codeql.yml

**Describe the solution you'd like**
Make use of https://github.com/dorny/paths-filter to only run the pipelines listed above in case of changes in:

https://github.com/ZEISS/czicompress/actions/workflows/czicompress_cmake.yml
https://github.com/ZEISS/czicompress/actions/workflows/czicompress_codeql.yml
-> Change in czicompress or ./ excluding czishrink

https://github.com/ZEISS/czicompress/actions/workflows/czishrink_dotnet.yml
https://github.com/ZEISS/czicompress/actions/workflows/czishrink_codeql.yml
-> Change in czishrink or ./ excluding czicompress

**Additional context**
https://stackoverflow.com/questions/70708306/github-actions-run-step-job-in-a-workflow-if-changes-happen-in-specific-folde
https://github.com/orgs/community/discussions/25669
https://how.wtf/run-workflow-step-or-job-based-on-file-changes-github-actions.html

In particular, status checks will still work/apply: 
https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks

**Comment by m-ringler** [comment]
We had path filters initially in PR #6, but we [removed them](https://github.com/ZEISS/czicompress/pull/6/commits/98531d404198a741b7fb8bb4556901e94e08bc74) because the respective github workflows were required PR checks (via branch protection rules). E. g. when you make changes to czishrink, a successful czicompress_cmake build is still required to be able to complete a PR targeting main.

**Comment by FelixS90** [comment]
> We had path filters initially in PR #6, but we [removed them](https://github.com/ZEISS/czicompress/pull/6/commits/98531d404198a741b7fb8bb4556901e94e08bc74) because the respective github workflows were required PR checks (via branch protection rules). E. g. when you make changes to czishrink, a successful czicompress_cmake build is still required to be able to complete a PR targeting main. So it would be required to 'path-filter' also the branch protection rules.

Thanks for your remark. Please refer to "Additional context" above. The workflow will not be skipped - the job will be skipped based on the outcome of https://github.com/dorny/paths-filter, i.e. it works on job/step level. Thus, individual jobs will be marked as skipped, which however makes the check pass/succeed.

**Comment by m-ringler** [comment]
I've abandoned the PRs #36 and #37. Nobody seems to work on this any more and there is no real urgency => closing the issue.
