### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by alexZhongvai** [ZEISS/czicompress#4]
It was nice to listen to your presentation at the I2K conference.
What is the difference between this czicompress and what is already available in the ZEN?

Thanks,
Alex

**Comment by m-ringler** [comment]
czicompress is a standalone tool and you can use it to compress a large number of (as yet uncompressed) CZI files (cf. the [example scripts in the Readme](https://github.com/ZEISS/czicompress/blob/main/README.md#examples)) - without having to open and 'save as' all of them in ZEN. The compression ratios should be similar for ZEN and czicompress.

In ZEN 'Save As with Options', you can also choose lossy compression (JpegXR), czicompress only offers lossless zstd compression.

Finally, czicompress is free software, it is cross-platform, and it is small. And ZEN is none of that.
