### ISSUE TITLE
List compression status of file

### ISSUE THREAD

**Issue by diego-rt** [ZEISS/czicompress#41]
Hello,

Is it possible to make the tool list the compression status of a CZI file? We would like to scan our local storage in search of uncompressed files.

Thanks!!

**Comment by m-ringler** [comment]
Hi @diego-rt, thanks for your interest in our CZI tools. Strictly speaking, a CZI file does not necessarily have a single compression status. The pixel data in a CZI file is organized into units called subblocks and each of these can be compressed (with one of various methods - one of which is zstd) or uncompressed. That said, most of the time, all subblocks have the same compression 'status'.

With 'the tool' are you referring to CZI Shrink (the UI tool), or would it be acceptable for you to use a command line tool? If so you could use [CZIcmd](https://zeiss.github.io/libczi/czicmd.html) from the [libczi](https://github.com/ZEISS/libczi) repo. The basic usage is 
~~~sh
CZIcmd -c PrintInformation -i AllSubblocks -s Your.czi
~~~
which will print something like
~~~
Complete list of sub-blocks
---------------------------

#0:  M=0 logical=(0,0,100,100) phys.=(100,100) pixeltype=gray16 compression=zstd1
#1:  M=1 logical=(100,0,100,100) phys.=(100,100) pixeltype=gray16 compression=zstd1
~~~
if your CZI is zstd-compressed, 
and something like
~~~
Complete list of sub-blocks
---------------------------

#0:  M=1 logical=(100,0,100,100) phys.=(100,100) pixeltype=gray16 compression=uncompressed
#1:  M=0 logical=(0,0,100,100) phys.=(100,100) pixeltype=gray16 compression=uncompressed
~~~
if your CZI is uncompressed.

With this, we can build a script that finds CZI files with at least one uncompressed subblock. Here's how you could do it for the bash shell (which is also available for windows; you can install it e. g. with the git installer):
* [Build libczi](https://zeiss.github.io/libczi/buildinglib_c_z_i.html) 
* Find the CZIcmd executable and put it on your path, for example like this:
 ~~~sh
path_to_czicmd=$(find $(pwd -P) \( -name CZIcmd -or -name CZIcmd.exe \) -type f -executable | head -n 1)
dir_of_czicmd=$(dirname "$path_to_czicmd")
PATH="$PATH:$dir_of_czicmd"
~~~
* Check that you can actually run CZIcmd
~~~sh
CZIcmd --version
~~~
* Create a short script file called `has_an_uncompressed_subblock.sh` with the following contents:
~~~sh
#/bin/bash
file="$1"
if CZIcmd -c PrintInformation -i AllSubblocks -s "$file" | grep -q 'compression=uncompressed'
then
  echo $file
fi
~~~
* Now you can run 
~~~sh
find /folder/to/search -iname '*.czi' -exec bash /path/to/has_an_uncompressed_subblock.sh '{}' \;
~~~
and it will output a list of files that have at least one uncompressed subblock. You can redirect the output to a file using `> list_of_uncompressed_czis.txt`.

**Comment by diego-rt** [comment]
Hi @m-ringler !

Thanks a lot for the fantastic and very informative explanation. This sounds exactly like what we need. I will give it a try with the command line tool.

Thank you!!!

**Comment by m-ringler** [comment]
If you have difficulties building CZIcmd please let us know (with the information which operating system you want to run it on). We can probably provide a compiled binary.

**Comment by m-ringler** [comment]
@diego-rt In my fork of the libczi repo, the build can now upload CZIcmd as pipeline artifacts. And you can download compiled CZIcmd binaries from e. g. https://github.com/m-ringler/libczi/actions/runs/7046393353

If you are on Windows, either of the 'win-x64' artifacts should work for you, I'd suggest that you try [CZIcmd-StreamsOFF-win-x64](https://github.com/m-ringler/libczi/suites/18633236508/artifacts/1083481149).

If you are on Linux, building yourself is probably the better option because
- it is unlikely that the libraries used on the github build runner are the same as on your machine
-  It's relatively straight-forward to make your own build on linux.
