### ISSUE TITLE
Use codecov to monitor code coverage

### ISSUE THREAD

**Issue by m-ringler** [ZEISS/czicompress#8]
We are already using it in:

https://github.com/ZEISS/libczi
https://github.com/ZEISS/imgdoc2
The nice thing is that you get PR comments, dashboards and everything else as part of one solution stack.

https://app.codecov.io/gh/ZEISS/libczi

Also: We do not need to rely on more/other community actions.

**Comment by m-ringler** [comment]
See PR comment https://github.com/ZEISS/czicompress/pull/6/files#r1386690970 by @FelixS90

**Comment by FelixS90** [comment]
Reminder: Remove the following actions from allowed actions once this issue is completed:

irongut/codecoveragesummary@v1.3.0
marocchino/sticky-pull-request-comment@v2
